### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sadorlovsky** [sadorlovsky/strunit#1]
Roadmap:
- [x] `px`, Pixels
- [x] `pt`, Points
- [x] `%`, Percents
- [x] `cm`, Centimeters
- [x] `mm`, Millimeters
- [x] `Q`, Quarter-millimeters
- [x] `in`, Inches
- [x] `pc`, Picas
- [x] `ex`, x-height of the element's font
- [x] `em`, Font size of the parent element
- [x] `rem`, Font size of the root element
- [x] `vw`, 1% of the viewport's width
- [x] `vh`, 1% of the viewport's height
- [x] `vmin`, 1% of the viewport's smaller dimension
- [x] `vmax`, 1% of the viewport's larger dimension
- [x] `ch`, The advance measure (width) of the glyph "0" of the element's font
- [x] custom unit, like `custom(value: number | string, unit: string)` or default import `strunit(value: number | string, unit: string)`
